sudo: required # necessary to use Trusty
dist: trusty

cache: apt

addons:
  apt:
    packages:
      - latexmk

      - texlive-latex-base
      - texlive-fonts-recommended
      - texlive-lang-cyrillic

      - texlive-latex-recommended
      - texlive-latex-extra # comment
      - texlive-science # physics

      - latex-xcolor # xcolor

script:
  - make wipe
  - make build
